mongo:
  image: mongo:3.0
  volumes_from:
    - data
  ports:
    - "27017:27017"

data:
  image: data

proxiapp:
  image: proxiapp
  ports:
    - "31201:31201"
  links:
    - mongo

nginx:
  image: nginx
  links:
    - proxiapp
  ports:
    - "8443:8443"
