#!/usr/bin/env node

/*
 * Command line interface for genData
 *
 * Usage:
 *
 *    node gen
 *    node gen --help
 */
var
  genData = require(__dirname + '/genData'),
  cli = require('commander')  // command line interface

cli
  .option('-u, --users <num>', 'users to generate [3]')
  .option('-b, --beacons <num>', 'beacons to generate [3]')
  .option('-e, --epb <num>', 'place entities per beacon [5]')
  .option('-s, --spe <num>', 'post entities per place [5]')
  .option('-c, --cpe <num>', 'comment entities per entity [5]')
  .option('-d, --database <database>', 'database name [proxTest]', String, 'proxTest')
  .option('-v, --validate', 'validate database inserts against schema')
  .option('-f, --files', 'create files rather than update the database')
  .option('-o, --out <dir>', 'output directory for files [files]', String, 'files')
  .parse(process.argv)

genData(cli)
