#!/usr/bin/env node

/*
 * Command line interface for genData
 *
 * Usage:
 *
 *    node gen
 *    node gen --help
 */
var
  genData = require(__dirname + '/genData'),
  cli = require('commander')  // command line interface

cli
  .option('-u, --users <num>', 'users to generate')
  .option('-b, --beacons <num>', 'beacons to generate')
  .option('-e, --epb <num>', 'place entities per beacon')
  .option('-a, --ape <num>', 'applink entities per place')
  .option('-s, --spe <num>', 'post entities per place')
  .option('-c, --cpe <num>', 'comment entities per post and place entity')
  .option('-l, --likes <num>', 'likes per entity and user')
  .option('-w, --watch <num>', 'watches per entiy and user')
  .option('-d, --database <database>', 'database name [proxTest]', String, 'proxTest')
  .parse(process.argv)

genData(cli)
