#!/usr/bin/env node

/*
 * Command line interface for genData
 *
 * Usage:
 *
 *    node gen
 *    node gen --help
 */
var
  genData = require(__dirname + '/genData'),
  cli = require('commander')  // command line interface

cli
  .option('-users, --users <num>', 'users to generate')
  .option('-ppu, --ppu <num>', 'patches per user')
  .option('-bpp, --bpp <num>', 'beacon per patch')
  .option('-ppp, --ppp <num>', 'places per patch')
  .option('-mpp, --mpp <num>', 'messages per patch')
  .option('-app, --app <num>', 'applinks per patch')
  .option('-d, --database <database>', 'database name [proxTest]', String, 'proxTest')
  .parse(process.argv)

genData(cli)
